name: mike is
markdown: redcarpet
highlighter: pygments
description: "mike is. mike writes"
url: "http://mike.is"

author:
  name: Michael Glass
  email: me@mike.is
  github: michaelglass
  twitter: michaelglass

gems:
  - jekyll-mentions
  - jemoji
  - jekyll-redirect-from